version: '3.1'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lex
      POSTGRES_PASSWORD: lex
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d/

  minio:
    image: minio/minio:latest
    volumes:
      - ./minio-data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: lex-minio
      MINIO_SECRET_KEY: lex-minio
    command: server /data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090