version: '3.1'

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lex
      POSTGRES_PASSWORD: lex
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d/

